#!/bin/sh

# Purpose: Execute every script under a directory,
#          for example, /etc/cron.daily/*
#

if [ -z $1 ]; then
   echo "Usage: $0 crondir"
   exit 1
fi

for cron in $1/* ; do
  if [ -x $cron ]; then
     $cron
  fi
done
unset cron
