#!/bin/bash
# Author : Anh K. Huynh
# Date   : 2013 Oct 18th
# License: MIT

pkgdesc="This package only contains :makepkg script from :pacman"

unset check
unset provides
unset conflicts
unset replaces
unset backup
unset install

depends=('pacman')

build() {
  _patch_and_config
  cd "$srcdir/$pkgname-theslinux-$pkgver/scripts"
  make
}

package() {
  cd $srcdir/$pkgname-theslinux-$pkgver
  install -dm755 $pkgdir/usr/bin/
  install -m755 "scripts/makepkg" $pkgdir/usr/bin
}
